export const CHANGE_CATALOG_CONTENT = 'CHANGE_CATALOG_CONTENT';
export const UPDATE_BOOK = 'UPDATE_BOOK';
export const CHOOSE_BOOK = 'CHOOSE_BOOK';
export const SETUP_AUTH_USER='SETUP_AUTH_USER';
export const SET_USER_REQUESTS='SET_USER_REQUESTS';