import React, { Component } from 'react';
import { Provider } from 'react-redux';
import actions from './actions';

import Application from './combo/Application';
import { store } from './config/store';

export default class App extends Component {
    componentDidMount() {
        // SplashScreen.hide();
        const gg = JSON.parse('[{"here":false,"literatureType":{"books":[],"name":"Fiction","id":1},"yearOfPublishing":2017,"author":{"firstName":"Jack","books":[],"id":4,"secondName":"London"},"genre":{"books":[],"name":"Fantasy","id":1},"publishingHouse":"ACT","onlyInReadingRoom":false,"numbOfPages":256,"id":12,"title":"Love of life"},{"here":false,"literatureType":{"books":[],"name":"Fiction","id":1},"yearOfPublishing":2014,"author":{"firstName":"Jack","books":[],"id":4,"secondName":"London"},"genre":{"books":[],"name":"Realism","id":10},"publishingHouse":"Azbyka","onlyInReadingRoom":false,"numbOfPages":357,"id":13,"title":"Son of the wolf"},{"here":true,"literatureType":{"books":[],"name":"Fiction","id":1},"yearOfPublishing":2007,"author":{"firstName":"Jack","books":[],"id":4,"secondName":"London"},"genre":{"books":[],"name":"Realism","id":10},"publishingHouse":"Xmo","onlyInReadingRoom":false,"numbOfPages":150,"id":15,"title":"The Scarlet Plague "},{"here":false,"literatureType":{"books":[],"name":"Fiction","id":1},"yearOfPublishing":1999,"author":{"firstName":"Joanne","books":[],"id":7,"secondName":"Rowling"},"genre":{"books":[],"name":"Fantasy","id":1},"publishingHouse":"POSMEN","numbOfPages":526,"id":16,"title":"Harry Potter"},{"here":true,"literatureType":{"books":[],"name":"Fiction","id":1},"yearOfPublishing":2014,"author":{"firstName":"Oscar","books":[],"id":5,"secondName":"Wilde"},"genre":{"books":[],"name":"Mystic","id":2},"publishingHouse":"Azbyka","numbOfPages":253,"id":17,"title":"The picture of Dorian Gray"},{"here":false,"literatureType":{"books":[],"name":"Fiction","id":1},"yearOfPublishing":2013,"author":{"firstName":"Brandon","books":[],"id":6,"secondName":"Sanderson"},"genre":{"books":[],"name":"Fantasy","id":1},"publishingHouse":"ClubSemeinogoDosyga","numbOfPages":1113,"id":18,"title":"The way of kings"},{"here":true,"literatureType":{"books":[],"name":"Reference","id":5},"yearOfPublishing":1888,"author":{"firstName":"Brandon","books":[],"id":6,"secondName":"Sanderson"},"genre":{"books":[],"name":"Fairytale","id":4},"publishingHouse":"sdfghjkl","onlyInReadingRoom":true,"numbOfPages":344,"id":21,"title":"sdfghjkl"}]');
        actions.changecatalogContent(gg);
        const str = JSON.parse(`[{"valid":true,"reader":{"roleCount":0,"roles":[],"credentialsNonExpired":true,"active":true,"issuanceRequest":[],"contactDetails":"Tyler@gmail.com","enabled":true,"authorities":[],"password":"1234","surname":"Tyler","name":"Rosa","accountNonExpired":true,"id":10,"username":"user","accountNonLocked":true},"book":{"here":false,"literatureType":{"books":[],"name":"Fiction","id":1},"yearOfPublishing":2017,"author":{"firstName":"Jack","books":[],"id":4,"secondName":"London"},"genre":{"books":[],"name":"Fantasy","id":1},"publishingHouse":"ACT","onlyInReadingRoom":false,"numbOfPages":256,"id":12,"title":"Love of life"},"name":"Love of life","id":29,"send":true,"accept":false},{"date":"2019-12-18 13:53:24.0","valid":true,"reader":{"roleCount":0,"roles":[],"credentialsNonExpired":true,"active":true,"issuanceRequest":[],"contactDetails":"Tyler@gmail.com","enabled":true,"authorities":[],"password":"1234","surname":"Tyler","name":"Rosa","accountNonExpired":true,"id":10,"username":"user","accountNonLocked":true},"book":{"here":false,"literatureType":{"books":[],"name":"Fiction","id":1},"yearOfPublishing":2014,"author":{"firstName":"Jack","books":[],"id":4,"secondName":"London"},"genre":{"books":[],"name":"Realism","id":10},"publishingHouse":"Azbyka","onlyInReadingRoom":false,"numbOfPages":357,"id":13,"title":"Son of the wolf"},"name":"Son of the wolf","id":31,"send":true,"accept":true},{"date":"2020-11-10 23:24:05.0","valid":true,"reader":{"roleCount":0,"roles":[],"credentialsNonExpired":true,"active":true,"issuanceRequest":[],"contactDetails":"Tyler@gmail.com","enabled":true,"authorities":[],"password":"1234","surname":"Tyler","name":"Rosa","accountNonExpired":true,"id":10,"username":"user","accountNonLocked":true},"book":{"here":false,"literatureType":{"books":[],"name":"Fiction","id":1},"yearOfPublishing":1999,"author":{"firstName":"Joanne","books":[],"id":7,"secondName":"Rowling"},"genre":{"books":[],"name":"Fantasy","id":1},"publishingHouse":"POSMEN","numbOfPages":526,"id":16,"title":"Harry Potter"},"name":"Harry Potter","id":33,"send":true,"accept":true},{"valid":true,"reader":{"roleCount":0,"roles":[],"credentialsNonExpired":true,"active":true,"issuanceRequest":[],"contactDetails":"Tyler@gmail.com","enabled":true,"authorities":[],"password":"1234","surname":"Tyler","name":"Rosa","accountNonExpired":true,"id":10,"username":"user","accountNonLocked":true},"book":{"here":false,"literatureType":{"books":[],"name":"Fiction","id":1},"yearOfPublishing":2013,"author":{"firstName":"Brandon","books":[],"id":6,"secondName":"Sanderson"},"genre":{"books":[],"name":"Fantasy","id":1},"publishingHouse":"ClubSemeinogoDosyga","numbOfPages":1113,"id":18,"title":"The way of kings"},"name":"The way of kings","id":34,"send":false,"accept":false}]`);
        actions.setRequests(str);
    }

    render() {
        return (
            <Provider store={store}>
                <Application />
            </Provider>
        );
    }
}